### PR TITLE
call scrollIntoViewIfNeeded only when available

### PR DESCRIPTION
**Pull request by mh-cbon**
fix an error with this method scrollIntoViewIfNeeded

### CODE REVIEW

**Comment by puranjayjain** [comment]
Can you also add a fallback scroll to year?

**Comment by mh-cbon** [comment]
what about using this stub ? https://gist.github.com/hsablonniere/2581101

**Comment by puranjayjain** [comment]
@mh-cbon I had earlier included it in the src but it didnt work in a compiled build of the script. It works though. Could you figure out a way such that it jumps into action for all users?

**Comment by mh-cbon** [comment]
> Could you figure out a way such that it jumps into action for all users?

great Q. Not sure i m keen to spend time on testing ie8 and the dozen others. Not sure how i should proceed either (i run no windows here). Maybe there s some online services to help me to deal with that. Any rec/guideline is welcome.

> I had earlier included it in the src but it didnt work in a compiled build of the script.

Let me give it a try.

**Pull request merged**
