### PR TITLE
Compiled themes, callbacks and "click outside to close"

### PR DESCRIPTION
**Pull request by alegag**
@puranjayjain I compiled the themes after my last PR (I had only updated the SCSS) and I also recompiled the JS from the ES source.

I've also added the callback functions "onOk" and "onCancel".

Issue #141 : Click outside the picker now close it.

Also, added two new callbacks, onShow and onHide.

### CODE REVIEW

**Comment by alegag** [comment]
@puranjayjain Callbacks were mentionned in Issue #52, but I'm not sure if it was all that was left to do there or not.  I'll let you check that issue back to know if you can close it or not.

**Comment by puranjayjain** [comment]
That's great aleg i'll look into all your work I need two more days after which I'm pretty much free

**Comment by alegag** [comment]
@puranjayjain About the two new callbacks, I use "onShow" to "blur" the inputbox so that on mobile-device, the keyboard doesn't show.

Might be good to update documentation with that information.

By the way, if you want me to contribute on the documentation page with the latest features I added, just let me know where/how !

I was thinking we could put a "basic example" in the README.md to give a quick insight ?

**Comment by alegag** [comment]
@puranjayjain Any complication with that PR ?

**Comment by puranjayjain** [comment]
None so far shall merge it today.

**Comment by alegag** [comment]
@puranjayjain I just did a new commit to add "hover" effect on the dial, and fix an "overlap" for the 24-hour mode.

Let me know if there is any trouble merging this !

**Comment by puranjayjain** [comment]
Can you fix the merge conflicts shown here?

**Comment by digitalkaoz** [comment]
@alegag can you please rebase your branch and fix the cs according the [hound.yml](https://houndci.com) configuration please?

**Comment by alegag** [comment]
@digitalkaoz I won't be able to do it in the next month or two.  I will write here once I can put time on this to make sure the pull request won't be delayed and put us in the situation we have right now again.  If I can get back to it before, I'll sure do !

**Pull request closed without merging**
