### PR TITLE
View not longer automatically switches from minute to hour. Hour view…

### PR DESCRIPTION
**Pull request by codingfriend1**
… waits for selection to register and animate before switching to minute view.

### CODE REVIEW

**Comment by codingfriend1** [comment]
I found one issue, when selecting the 00 minutes in the minute view it selects 15 minutes instead.

**Comment by puranjayjain** [comment]
thanks @codingfriend1 for the PR it was something that was bothering me for quite some time. It seems we might soon roll out the next release.

**Comment by codingfriend1** [comment]
When can we expect this feature to be released?

**Comment by puranjayjain** [comment]
I will try to release it by 6th of Feb

**Comment by puranjayjain** [comment]
Am not getting a lot of time these days will try to get it done asap!

**Comment by puranjayjain** [comment]
merging it though may need to make changes on top of it

**Pull request merged**
